name: Clean up
description: Clean up

inputs:
  folder_path:
    description: "Relative folder path"
    required: true

runs:
  using: "composite"
  steps:
    - name: Clean up
      run: |
        cd ${FOLDER_PATH}
        git clean -xdf
      env:
        FOLDER_PATH: ${{ inputs.folder_path }}
      shell: bash
