name: Clone test data
description: Clone test data repository

runs:
  using: "composite"
  steps:
    - name: Clone test data repository
      run: |
        mkdir -p test-data
        git config --global user.name "GitHub Actions"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git clone https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/RBniCS/RBniCS-test-data test-data/RBniCS
        echo "::set-env name=ROOT_DIR::${PWD}"
        echo "::set-env name=DATA_DIR::${PWD}/test-data/RBniCS"
      shell: bash
