name: Parse matrix
description: Parse matrix for tutorials runs

inputs:
  matrix_which:
    description: "Variable of the matrix stategy, containing one slash"
    required: true
  folder_name_variable:
    description: "Environment variable name in which to store the name of the folder"
    required: true
  file_name_variable:
    description: "Environment variable name in which to store the name of the file"
    required: true

runs:
  using: "composite"
  steps:
    - name: Parse matrix for tutorials runs
      run: |
        echo "::set-env name=${{ inputs.folder_name_variable }}::$(echo ${{ inputs.matrix_which }} | cut -d'/' -f1)"
        echo "::set-env name=${{ inputs.file_name_variable }}::$(echo ${{ inputs.matrix_which }} | cut -d'/' -f2)"
      shell: bash
