name: Install RBniCS
description: Install RBniCS and its dependencies

runs:
  using: "composite"
  steps:
    - name: Install RBniCS dependencies
      run: pip3 -q install --upgrade cvxopt gitpython multipledispatch pylru pytest pytest-benchmark pytest-dependency pytest-flake8 pytest-gc pytest-xdist sympy toposort
      shell: bash
    - name: Install RBniCS
      run: |
        python3 setup.py -q install
        python3 -c "import dolfin; import rbnics"
      shell: bash
