name: RBniCS CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 2 * * MON"

jobs:
  test:
    if: "!(contains(github.event.head_commit.message, '[ci skip]') || contains(github.event.head_commit.message, '[skip ci]'))"
    runs-on: ubuntu-latest
    container: quay.io/fenicsproject/dev
    steps:
      - uses: actions/checkout@v2

  docker:
    if: github.repository == 'RBniCS/RBniCS'
    runs-on: ubuntu-latest
    needs: [test]
    env:
      RELEASE_IMAGE: ${{ secrets.CI_REGISTRY_IMAGE }}:latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the docker testing image
        run: docker build --pull -t ${RELEASE_IMAGE} -f docker/Dockerfile .
      - name: Log into the docker registry
        run: docker login -u ${{ secrets.CI_REGISTRY_USER }} -p ${{ secrets.CI_REGISTRY_PASSWORD }} ${{ secrets.CI_REGISTRY }}
      - name: Push to the docker registry
        run: docker push ${RELEASE_IMAGE}
