name: RBniCS CI (slow tests)

on:
  schedule:
    - cron: "0 21 * * MON"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container: quay.io/fenicsproject/dev
    steps:
      - uses: actions/checkout@v2
      - name: Install RBniCS
        uses: ./.github/actions/install
      - name: Run pull back to reference domain tests
        run: pytest -n auto tests/unit/test_pull_back_to_reference_domain.py
      - name: Run performance tests
        run: pytest -n auto tests/performance
