name: RBniCS methodology tests

on:
  schedule:
    - cron: "0 21 * * TUE"
  workflow_dispatch:
    inputs:
      required_action:
        description: "Action to run (compare or regold)"
      required_parallelism:
        description: "Parallelism to be employed when running the test (serial, parallel or both)"
      only_on_folder_name:
        description: "Run only on folder name (eim is currently the only valid value)"
      only_on_test_number:
        description: "Run only on test number"

jobs:
  test:
    runs-on: ubuntu-latest
    container: quay.io/fenicsproject/dev
    strategy:
      matrix:
        which: [eim/00, eim/01, eim/02, eim/03, eim/04, eim/05, eim/06, eim/07, eim/08, eim/09,
          eim/10, eim/11, eim/12, eim/13, eim/14, eim/15, eim/16, eim/17, eim/18, eim/19,
          eim/20, eim/21, eim/22, eim/23]
      fail-fast: false
    steps:
      - uses: actions/checkout@v1  # @v2 cannot be used because container image has old version of git
      - name: Get folder name and test number
        uses: ./.github/actions/tutorials/parse_matrix
        with:
          matrix_which: ${{ matrix.which }}
          folder_name_variable: FOLDER_NAME
          file_name_variable: TEST_NUMBER
      - name: Get required action (compare or regold) and required parallelism (serial, parallel or both)
        uses: ./.github/actions/tutorials/parse_workflow_dispatch
        with:
          required_action: ${{ github.event.inputs.required_action }}
          required_parallelism: ${{ github.event.inputs.required_parallelism }}
          only_on_folder_name: ${{ github.event.inputs.only_on_folder_name }}
          only_on_file_name: ${{ github.event.inputs.only_on_test_number }}
          current_folder_name: ${{ env.FOLDER_NAME }}
          current_file_name: ${{ env.TEST_NUMBER }}
      - name: Install RBniCS
        if: env.REQUIRED_ACTION == 'compare' || env.REQUIRED_ACTION == 'regold'
        uses: ./.github/actions/install
      - name: Clone test data repository
        if: env.REQUIRED_ACTION == 'compare' || env.REQUIRED_ACTION == 'regold'
        uses: ./.github/actions/test_data/clone
        with:
          branch: master
        env:
          GIT_USERNAME: ${{ secrets.MIRROR_GITHUB_USER }}
          GIT_PASSWORD: ${{ secrets.MIRROR_GITHUB_TOKEN }}
      - name: Regold methodology tests (serial)
        if: >-
          env.REQUIRED_ACTION == 'regold' &&
          (env.REQUIRED_PARALLELISM == 'serial' || env.REQUIRED_PARALLELISM == 'serial_parallel')
        uses: ./.github/actions/tutorials/run_action
        with:
          action: "regold"
          pytest: "pytest -n auto"
          folder_path: "tests/methodology/${{ env.FOLDER_NAME }}"
          file_name: "test_${{ env.FOLDER_NAME }}_approximation_${{ env.TEST_NUMBER}}.py"
      - name: Clean up regolded results (serial)
        if: >-
          env.REQUIRED_ACTION == 'regold' &&
          (env.REQUIRED_PARALLELISM == 'serial' || env.REQUIRED_PARALLELISM == 'serial_parallel')
        uses: ./.github/actions/tutorials/clean_up
        with:
          folder_path: "tests/methodology/${{ env.FOLDER_NAME }}"
      - name: Run methodology tests (serial, offline and online)
        if: >-
          (env.REQUIRED_ACTION == 'compare' || env.REQUIRED_ACTION == 'regold') &&
          (env.REQUIRED_PARALLELISM == 'serial' || env.REQUIRED_PARALLELISM == 'serial_parallel')
        uses: ./.github/actions/tutorials/run_action
        with:
          action: "compare"
          pytest: "pytest -n auto"
          folder_path: "tests/methodology/${{ env.FOLDER_NAME }}"
          file_name: "test_${{ env.FOLDER_NAME }}_approximation_${{ env.TEST_NUMBER}}.py"
      - name: Run methodology tests (serial, online only)
        if: >-
          (env.REQUIRED_ACTION == 'compare' || env.REQUIRED_ACTION == 'regold') &&
          (env.REQUIRED_PARALLELISM == 'serial' || env.REQUIRED_PARALLELISM == 'serial_parallel')
        uses: ./.github/actions/tutorials/run_action
        with:
          action: "compare"
          pytest: "pytest -n auto"
          folder_path: "tests/methodology/${{ env.FOLDER_NAME }}"
          file_name: "test_${{ env.FOLDER_NAME }}_approximation_${{ env.TEST_NUMBER}}.py"
#      - name: Run methodology tests (parallel from serial, online only) - not working due to empty mesh on one process
#        if: >-
#          (env.REQUIRED_ACTION == 'compare' || env.REQUIRED_ACTION == 'regold') &&
#          (env.REQUIRED_PARALLELISM == 'serial' || env.REQUIRED_PARALLELISM == 'serial_parallel')
#        uses: ./.github/actions/tutorials/run_action
#        with:
#          action: "compare"
#          pytest: "mpirun -n 2 pytest --gc-disable --gc-scope function"
#          folder_path: "tests/methodology/${{ env.FOLDER_NAME }}"
#          file_name: "test_${{ env.FOLDER_NAME }}_approximation_${{ env.TEST_NUMBER}}.py"
      - name: Clean up results (serial)
        if: >-
          (env.REQUIRED_ACTION == 'compare' || env.REQUIRED_ACTION == 'regold') &&
          (env.REQUIRED_PARALLELISM == 'serial' || env.REQUIRED_PARALLELISM == 'serial_parallel')
        uses: ./.github/actions/tutorials/clean_up
        with:
          folder_path: "tests/methodology/${{ env.FOLDER_NAME }}"
      - name: Regold methodology tests (parallel)
        if: >-
          env.REQUIRED_ACTION == 'regold' &&
          (env.REQUIRED_PARALLELISM == 'parallel' || env.REQUIRED_PARALLELISM == 'serial_parallel')
        uses: ./.github/actions/tutorials/run_action
        with:
          action: "regold"
          pytest: "mpirun -n 2 pytest --gc-disable --gc-scope function"
          folder_path: "tests/methodology/${{ env.FOLDER_NAME }}"
          file_name: "test_${{ env.FOLDER_NAME }}_approximation_${{ env.TEST_NUMBER}}.py"
      - name: Clean up regolded results (parallel)
        if: >-
          env.REQUIRED_ACTION == 'regold' &&
          (env.REQUIRED_PARALLELISM == 'parallel' || env.REQUIRED_PARALLELISM == 'serial_parallel')
        uses: ./.github/actions/tutorials/clean_up
        with:
          folder_path: "tests/methodology/${{ env.FOLDER_NAME }}"
      - name: Run methodology tests (parallel, offline and online)
        if: >-
          (env.REQUIRED_ACTION == 'compare' || env.REQUIRED_ACTION == 'regold') &&
          (env.REQUIRED_PARALLELISM == 'parallel' || env.REQUIRED_PARALLELISM == 'serial_parallel')
        uses: ./.github/actions/tutorials/run_action
        with:
          action: "compare"
          pytest: "mpirun -n 2 pytest --gc-disable --gc-scope function"
          folder_path: "tests/methodology/${{ env.FOLDER_NAME }}"
          file_name: "test_${{ env.FOLDER_NAME }}_approximation_${{ env.TEST_NUMBER}}.py"
      - name: Run methodology tests (parallel, online only)
        if: >-
          (env.REQUIRED_ACTION == 'compare' || env.REQUIRED_ACTION == 'regold') &&
          (env.REQUIRED_PARALLELISM == 'parallel' || env.REQUIRED_PARALLELISM == 'serial_parallel')
        uses: ./.github/actions/tutorials/run_action
        with:
          action: "compare"
          pytest: "mpirun -n 2 pytest --gc-disable --gc-scope function"
          folder_path: "tests/methodology/${{ env.FOLDER_NAME }}"
          file_name: "test_${{ env.FOLDER_NAME }}_approximation_${{ env.TEST_NUMBER}}.py"
#      - name: Run methodology tests (serial from parallel, online only) - need to mix gold results in the comparison
#        if: >-
#          (env.REQUIRED_ACTION == 'compare' || env.REQUIRED_ACTION == 'regold') &&
#          (env.REQUIRED_PARALLELISM == 'parallel' || env.REQUIRED_PARALLELISM == 'serial_parallel')
#        uses: ./.github/actions/tutorials/run_action
#        with:
#          action: "compare"
#          pytest: "pytest -n auto"
#          folder_path: "tests/methodology/${{ env.FOLDER_NAME }}"
#          file_name: "test_${{ env.FOLDER_NAME }}_approximation_${{ env.TEST_NUMBER}}.py"
      - name: Clean up results (parallel)
        if: >-
          (env.REQUIRED_ACTION == 'compare' || env.REQUIRED_ACTION == 'regold') &&
          (env.REQUIRED_PARALLELISM == 'parallel' || env.REQUIRED_PARALLELISM == 'serial_parallel')
        uses: ./.github/actions/tutorials/clean_up
        with:
          folder_path: "tests/methodology/${{ env.FOLDER_NAME }}"
      - name: Push regolded test data
        if: env.REQUIRED_ACTION == 'regold'
        uses: ./.github/actions/test_data/push
      - name: Store diffs on failure
        if: (env.REQUIRED_ACTION == 'compare' || env.REQUIRED_ACTION == 'regold') && failure()
        uses: actions/upload-artifact@v2
        with:
          name: diff_${{ env.FOLDER_NAME }}_${{ env.TEST_NUMBER }}
          path: tests/methodology/${{ env.FOLDER_NAME }}/**/*_diff
