name: RBniCS methodology tests

on:
  schedule:
    - cron: "0 2 * * WED"
  workflow_dispatch:
    inputs:
      required_action:
        description: 'Action to run (compare or regold)'
      only_on_folder_name:
        description: 'Run only on folder name'
      only_on_test_number:
        description: 'Run only on test number'

jobs:
  test:
    runs-on: ubuntu-latest
    container: quay.io/fenicsproject/dev
    strategy:
      matrix:
        which: [eim/00, eim/01, eim/02, eim/03, eim/04]
      fail-fast: false
    steps:
      - uses: actions/checkout@v1  # @v2 cannot be used because container image has old version of git
      - name: Get folder name and test number
        uses: ./.github/actions/tutorials/parse_matrix
        with:
          matrix_which: ${{ matrix.which }}
          folder_name_variable: FOLDER_NAME
          file_name_variable: TEST_NUMBER
      - name: Get required action (compare or regold)
        uses: ./.github/actions/tutorials/parse_workflow_dispatch
        with:
          required_action: ${{ github.event.inputs.regoldFolderName }}
          only_on_folder_name: ${{ github.event.inputs.only_on_folder_name }}
          only_on_file_name: ${{ github.event.inputs.only_on_test_number }}
          current_folder_name: ${{ env.FOLDER_NAME }}
          current_file_name: ${{ env.TEST_NUMBER }}
      - name: Install RBniCS
        if: env.REQUIRED_ACTION == 'compare' || env.REQUIRED_ACTION == 'regold'
        uses: ./.github/actions/install
      - name: Clone test data repository
        if: env.REQUIRED_ACTION == 'compare' || env.REQUIRED_ACTION == 'regold'
        run: |
          mkdir -p test-data
          git config --global user.name "GitHub Actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git clone https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/RBniCS/RBniCS-test-data test-data/RBniCS
          echo "::set-env name=ROOT_DIR::${PWD}"
          echo "::set-env name=DATA_DIR::${PWD}/test-data/RBniCS"
        env:
          GIT_USERNAME: ${{ secrets.MIRROR_GITHUB_USER }}
          GIT_PASSWORD: ${{ secrets.MIRROR_GITHUB_TOKEN }}
      - name: Regold methodology tests (serial)
        if: env.REQUIRED_ACTION == 'regold'
        run: |
          cd tests/methodology/${FOLDER_NAME}
          pytest -n auto test_${FOLDER_NAME}_approximation_${TEST_NUMBER}.py --data-dir ${DATA_DIR} --rootdir ${ROOT_DIR} --action regold
      - name: Clean up regolded results (serial)
        if: env.REQUIRED_ACTION == 'regold'
        run: |
          cd tests/methodology/${FOLDER_NAME}
          git clean -xdf
      - name: Run methodology tests (serial, offline and online)
        if: env.REQUIRED_ACTION == 'compare' || env.REQUIRED_ACTION == 'regold'
        run: |
          cd tests/methodology/${FOLDER_NAME}
          pytest -n auto test_${FOLDER_NAME}_approximation_${TEST_NUMBER}.py --data-dir ${DATA_DIR} --rootdir ${ROOT_DIR} --action compare
      - name: Run methodology tests (serial, online only)
        if: env.REQUIRED_ACTION == 'compare' || env.REQUIRED_ACTION == 'regold'
        run: |
          cd tests/methodology/${FOLDER_NAME}
          pytest -n auto test_${FOLDER_NAME}_approximation_${TEST_NUMBER}.py --data-dir ${DATA_DIR} --rootdir ${ROOT_DIR} --action compare
#      - name: Run methodology tests (parallel from serial, online only) - not working due to empty mesh on one process
#        if: env.REQUIRED_ACTION == 'compare'
#        run: |
#          cd tests/methodology/${FOLDER_NAME}
#          mpirun -n 2 pytest --gc-disable --gc-scope function test_${FOLDER_NAME}_approximation_${TEST_NUMBER}.py --data-dir ${DATA_DIR} --rootdir ${ROOT_DIR} --action compare
      - name: Clean up results (serial)
        if: env.REQUIRED_ACTION == 'compare' || env.REQUIRED_ACTION == 'regold'
        run: |
          cd tests/methodology/${FOLDER_NAME}
          git clean -xdf
      - name: Regold methodology tests (parallel)
        if: env.REQUIRED_ACTION == 'regold'
        run: |
          cd tests/methodology/${FOLDER_NAME}
          mpirun -n 2 pytest --gc-disable --gc-scope function test_${FOLDER_NAME}_approximation_${TEST_NUMBER}.py --data-dir ${DATA_DIR} --rootdir ${ROOT_DIR} --action regold
      - name: Clean up regolded results (parallel)
        if: env.REQUIRED_ACTION == 'regold'
        run: |
          cd tests/methodology/${FOLDER_NAME}
          git clean -xdf
      - name: Run methodology tests (parallel, offline and online)
        if: env.REQUIRED_ACTION == 'compare' || env.REQUIRED_ACTION == 'regold'
        run: |
          cd tests/methodology/${FOLDER_NAME}
          mpirun -n 2 pytest --gc-disable --gc-scope function test_${FOLDER_NAME}_approximation_${TEST_NUMBER}.py --data-dir ${DATA_DIR} --rootdir ${ROOT_DIR} --action compare
      - name: Run methodology tests (parallel, online only)
        if: env.REQUIRED_ACTION == 'compare' || env.REQUIRED_ACTION == 'regold'
        run: |
          cd tests/methodology/${FOLDER_NAME}
          mpirun -n 2 pytest --gc-disable --gc-scope function test_${FOLDER_NAME}_approximation_${TEST_NUMBER}.py --data-dir ${DATA_DIR} --rootdir ${ROOT_DIR} --action compare
#      - name: Run methodology tests (serial from parallel, online only) - need to mix gold results in the comparison
#        if: env.REQUIRED_ACTION == 'compare' || env.REQUIRED_ACTION == 'regold'
#        run: |
#          cd tests/methodology/${FOLDER_NAME}
#          pytest -n auto test_${FOLDER_NAME}_approximation_${TEST_NUMBER}.py --data-dir ${DATA_DIR} --rootdir ${ROOT_DIR} --action compare
      - name: Clean up results (parallel)
        if: env.REQUIRED_ACTION == 'compare' || env.REQUIRED_ACTION == 'regold'
        run: |
          cd tests/methodology/${FOLDER_NAME}
          git clean -xdf
      - name: Push regolded test data
        if: env.REQUIRED_ACTION == 'regold'
        run: |
          cd ${DATA_DIR}
          git push
      - name: Store diffs on failure
        if: (env.REQUIRED_ACTION == 'compare' || env.REQUIRED_ACTION == 'regold') && failure()
        uses: actions/upload-artifact@v2
        with:
          name: diff_${{ env.FOLDER_NAME }}_${{ env.TEST_NUMBER }}
          path: tests/methodology/${{ env.FOLDER_NAME }}/**/*_diff
