name: RBniCS methodology tests

on:
  schedule:
    - cron: "0 2 * * WED"
  workflow_dispatch:
    inputs:
      regoldFolderName:
        description: 'Folder to regold'
      regoldTestNumber:
        description: 'Test number to regold'

jobs:
  test:
    runs-on: ubuntu-latest
    container: quay.io/fenicsproject/dev
    strategy:
      matrix:
        which: [eim_00, eim_01, eim_02, eim_03]
      fail-fast: false
    steps:
      - uses: actions/checkout@v1  # @v2 cannot be used because container image has old version of git
      - name: Get folder name and test number
        run: |
          echo "::set-env name=FOLDER_NAME::$(echo ${{ matrix.which }} | cut -d'_' -f1)"
          echo "::set-env name=TEST_NUMBER::$(echo ${{ matrix.which }} | cut -d'_' -f2)"
      - name: Get required action (compare or regold)
        run: |
          echo "::set-env name=FOLDER_NAME::$(echo ${{ matrix.which }} | cut -d'_' -f1)"
          if [ "${REGOLD_FOLDER_NAME}" != "" ] && \
             [ "${REGOLD_TEST_NUMBER}" != "" ]; then
            if [ "${REGOLD_FOLDER_NAME}" = "${FOLDER_NAME}" ] && \
               [ "${REGOLD_TEST_NUMBER}" = "${TEST_NUMBER}" ]; then
              REQUIRED_ACTION="regold"
            else
              REQUIRED_ACTION="skip"
            fi
          else
            REQUIRED_ACTION="compare"
          fi
          echo "::set-env name=REQUIRED_ACTION::${REQUIRED_ACTION}"
        env:
          REGOLD_FOLDER_NAME: ${{ github.event.inputs.regoldFolderName }}
          REGOLD_TEST_NUMBER: ${{ github.event.inputs.regoldTestNumber }}
      - name: Install RBniCS dependencies
        if: env.REQUIRED_ACTION == 'compare' || env.REQUIRED_ACTION == 'regold'
        run: pip3 -q install --upgrade cvxopt gitpython multipledispatch pylru pytest pytest-benchmark pytest-dependency pytest-flake8 pytest-gc pytest-xdist sympy toposort
      - name: Install RBniCS
        if: env.REQUIRED_ACTION == 'compare' || env.REQUIRED_ACTION == 'regold'
        run: |
          python3 setup.py -q install
          python3 -c "import dolfin; import rbnics"
      - name: Clone test data repository
        if: env.REQUIRED_ACTION == 'compare' || env.REQUIRED_ACTION == 'regold'
        run: |
          mkdir -p test-data
          git config --global user.name "GitHub Actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git clone https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/RBniCS/RBniCS-test-data test-data/RBniCS
          echo "::set-env name=ROOT_DIR::${PWD}"
          echo "::set-env name=DATA_DIR::${PWD}/test-data/RBniCS"
        env:
          GIT_USERNAME: ${{ secrets.MIRROR_GITHUB_USER }}
          GIT_PASSWORD: ${{ secrets.MIRROR_GITHUB_TOKEN }}
      - name: Regold methodology tests (serial)
        if: env.REQUIRED_ACTION == 'regold'
        run: |
          cd tests/methodology/${FOLDER_NAME}
          pytest -n auto test_${FOLDER_NAME}_approximation_${TEST_NUMBER}.py --data-dir ${DATA_DIR} --rootdir ${ROOT_DIR} --action regold
      - name: Clean up regolded results (serial)
        if: env.REQUIRED_ACTION == 'regold'
        run: |
          cd tests/methodology/${FOLDER_NAME}
          git clean -xdf
      - name: Run methodology tests (serial, offline and online)
        if: env.REQUIRED_ACTION == 'compare' || env.REQUIRED_ACTION == 'regold'
        run: |
          cd tests/methodology/${FOLDER_NAME}
          pytest -n auto test_${FOLDER_NAME}_approximation_${TEST_NUMBER}.py --data-dir ${DATA_DIR} --rootdir ${ROOT_DIR} --action compare
      - name: Run methodology tests (serial, online only)
        if: env.REQUIRED_ACTION == 'compare' || env.REQUIRED_ACTION == 'regold'
        run: |
          cd tests/methodology/${FOLDER_NAME}
          pytest -n auto test_${FOLDER_NAME}_approximation_${TEST_NUMBER}.py --data-dir ${DATA_DIR} --rootdir ${ROOT_DIR} --action compare
#      - name: Run methodology tests (parallel from serial, online only) - not working due to empty mesh on one process
#        if: env.REQUIRED_ACTION == 'compare'
#        run: |
#          cd tests/methodology/${FOLDER_NAME}
#          mpirun -n 2 pytest --gc-disable --gc-scope function test_${FOLDER_NAME}_approximation_${TEST_NUMBER}.py --data-dir ${DATA_DIR} --rootdir ${ROOT_DIR} --action compare
      - name: Clean up results (serial)
        if: env.REQUIRED_ACTION == 'compare' || env.REQUIRED_ACTION == 'regold'
        run: |
          cd tests/methodology/${FOLDER_NAME}
          git clean -xdf
      - name: Regold methodology tests (parallel)
        if: env.REQUIRED_ACTION == 'regold'
        run: |
          cd tests/methodology/${FOLDER_NAME}
          mpirun -n 2 pytest --gc-disable --gc-scope function test_${FOLDER_NAME}_approximation_${TEST_NUMBER}.py --data-dir ${DATA_DIR} --rootdir ${ROOT_DIR} --action regold
      - name: Clean up regolded results (parallel)
        if: env.REQUIRED_ACTION == 'regold'
        run: |
          cd tests/methodology/${FOLDER_NAME}
          git clean -xdf
      - name: Run methodology tests (parallel, offline and online)
        if: env.REQUIRED_ACTION == 'compare' || env.REQUIRED_ACTION == 'regold'
        run: |
          cd tests/methodology/${FOLDER_NAME}
          mpirun -n 2 pytest --gc-disable --gc-scope function test_${FOLDER_NAME}_approximation_${TEST_NUMBER}.py --data-dir ${DATA_DIR} --rootdir ${ROOT_DIR} --action compare
      - name: Run methodology tests (parallel, online only)
        if: env.REQUIRED_ACTION == 'compare' || env.REQUIRED_ACTION == 'regold'
        run: |
          cd tests/methodology/${FOLDER_NAME}
          mpirun -n 2 pytest --gc-disable --gc-scope function test_${FOLDER_NAME}_approximation_${TEST_NUMBER}.py --data-dir ${DATA_DIR} --rootdir ${ROOT_DIR} --action compare
#      - name: Run methodology tests (serial from parallel, online only) - need to mix gold results in the comparison
#        if: env.REQUIRED_ACTION == 'compare' || env.REQUIRED_ACTION == 'regold'
#        run: |
#          cd tests/methodology/${FOLDER_NAME}
#          pytest -n auto test_${FOLDER_NAME}_approximation_${TEST_NUMBER}.py --data-dir ${DATA_DIR} --rootdir ${ROOT_DIR} --action compare
      - name: Clean up results (parallel)
        if: env.REQUIRED_ACTION == 'compare' || env.REQUIRED_ACTION == 'regold'
        run: |
          cd tests/methodology/${FOLDER_NAME}
          git clean -xdf
      - name: Push regolded test data
        if: env.REQUIRED_ACTION == 'regold'
        run: |
          cd ${DATA_DIR}
          git push
      - name: Store diffs on failure
        if: (env.REQUIRED_ACTION == 'compare' || env.REQUIRED_ACTION == 'regold') && failure()
        uses: actions/upload-artifact@v2
        with:
          name: diff_${{ env.FOLDER_NAME }}_${{ env.TEST_NUMBER }}
          path: tests/methodology/${{ env.FOLDER_NAME }}/**/*_diff
