name: RBniCS extra tutorials

on:
  schedule:
    - cron: "0 21 * * THU"
  workflow_dispatch:

jobs:
  test:
    if: >-
      (github.event_name == 'schedule' && github.repository == 'RBniCS/RBniCS')
      || (github.event_name != 'schedule')
    runs-on: ubuntu-latest
    container: quay.io/fenicsproject/dev
    steps:
      - uses: actions/checkout@v2
