name: RBniCS tutorials

on:
  schedule:
    - cron: "0 2 * * THU"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container: quay.io/fenicsproject/dev
    steps:
      - uses: actions/checkout@v2
